### PR TITLE
Add piece points. (Read code comments first before merging)

### PR DESCRIPTION
**Pull request by JushBJJ**
King: 0 points
Queen: 9 points
Rook: 5 points
Bishop and Horse: 3 points
Pawn: 1 point.

### CODE REVIEW

**Comment by viown** [comment]
but why

**Comment by JushBJJ** [comment]
to count how many points the player has.

[Opponent points here]
[Board]
[Your points here]

**Comment by viown** [comment]
Why should the chess engine care how many points the player is ahead?

**Comment by viown** [comment]
And did you just call it a "Horse"

**Pull request merged**
